### ISSUE TITLE
Use the original liche repository

### ISSUE THREAD

**Issue by dmitry-at-hyla** [3scale-ops/soyuz#7]
Now [Dockerfile](/3scale/soyuz/blob/main/Dockerfile#L5) and [Dockerfile-ci](/3scale/soyuz/blob/main/Dockerfile-ci#L8) use liche fork `dmitry-at-hyla/liche`. This fork has been created just to address issue [#25](https://github.com/raviqqe/liche/issues/25) from the original repository. Right now it is already fixed and merged in PR [#38](https://github.com/raviqqe/liche/pull/38). There is no reason to continue using this fork, please switch to the original repository (just replace `dmitry-at-hyla` with `raviqqe`).

P.S. BTW liche is deprecated now, consider using [muffet](https://github.com/raviqqe/muffet) instead.

**Comment by raelga** [comment]
Thank you very much @dmitry-at-hyla por the heads up.

And thanks for pointing us to `muffet`, but we are using it for markdown files and seems like is not supported by `muffet`. We probably move to https://github.com/lycheeverse/lychee, but as it affects to several of our repos. So we will start pointing back to the original repo, and eventually move to a new tool on all our repos.

**Comment by dmitry-at-hyla** [comment]
Nice to hear.

Yes, lychee is good. I switched to use it from liche.
